seeder:
  file: ./seeder/seeder.rb
  disabled: false
parsers:
  - page_type: listings
    file: ./parsers/listings.rb
  - page_type: job
    file: ./parsers/job.rb
exporters:
  - file: ./exporters/jobs_json.yaml
  - file: ./exporters/jobs_csv.yaml
